---
# tasks file for nifi
- name: Create nifi user and group
  user:
    name: nifi
    state: present
    createhome: no
    #uid: "{{ nifi_user_pid }}"

- name: Ensure nifi files are world-readable
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    owner: nifi
    group: nifi
    #mode: "a+rX"

  with_items:
    - "{{ nifi_base_dir }}"
    - "{{ nifi_etc_dir }}"
    - "{{ nifi_log_dir }}"
    - "{{ nifi_pid_dir }}"
    - "{{ nifi_data_dir }}"

- name: Download NiFi binaries for version {{ nifi_version }}
  unarchive:
    src: "http://apache.uib.no/nifi/{{ nifi_version }}/nifi-{{ nifi_version }}-bin.tar.gz"
    dest: "{{ nifi_base_dir }}"
    owner: nifi
    group: nifi
    remote_src: yes
    creates: "{{ nifi_base_dir }}/nifi-{{ nifi_version }}/bin/nifi.sh"

- name: Download NiFi-Toolkit binaries for version {{ nifi_version }}
  unarchive:
    src: "http://apache.uib.no/nifi/{{ nifi_version }}/nifi-toolkit-{{ nifi_version }}-bin.tar.gz"
    dest: "{{ nifi_base_dir }}"
    owner: nifi
    group: nifi
    remote_src: yes
    creates: "{{ nifi_base_dir }}/nifi-toolkit-{{ nifi_version }}/bin/tls-toolkit.sh"

- name: Ensure nifi-toolkit symlink
  file:
    src: "{{ nifi_base_dir }}/nifi-toolkit-{{ nifi_version }}"
    dest: "{{ nifi_toolkit_home }}"
    state: link
    owner: nifi
    group: nifi

- name: Create nifi-toolkit tls-server config
  when: inventory_hostname in groups['tls_server']
  template:
    src: tls-config-server.json
    dest: "{{ nifi_base_dir }}/nifi-toolkit-{{ nifi_version }}/conf/config-server.json"
    owner: nifi
    group: nifi
    mode: 0600
  notify: restart nifi-toolkit

- name: Create nifi-toolkit systemd service
  when: inventory_hostname in groups['tls_server']
  template:
    src: nifi-toolkit.service.j2
    dest: "{{ nifi_toolkit_service }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemctl
    - restart nifi-toolkit

- meta: flush_handlers

- name: Setup nifi client sertificates
  command: "{{ nifi_base_dir }}/nifi-toolkit-{{ nifi_version }}/bin/tls-toolkit.sh client -c {{ nifi_tls_server }} -t {{ nifi_tls_token }} -p {{ nifi_tls_port }}"
  args:
    chdir: "{{ nifi_etc_dir }}"
    creates: "{{ nifi_etc_dir }}/nifi-cert.pem"


- name: Ensure nifi symlink
  file:
    src: "{{ nifi_base_dir }}/nifi-{{ nifi_version }}"
    dest: "{{ nifi_home }}"
    state: link
    owner: nifi
    group: nifi
  notify:
    - restart nifi

- name: Create nifi systemd service
  template: src=nifi.service.j2 dest="{{ nifi_service }}" owner=root group=root mode=0644
  notify:
    - reload systemctl
    - restart nifi
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version >= "7"
  tags: [ service ]

- name: Ensure nifi-required directories exist and are world-readable
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ nifi_user }}"
    group: "{{ nifi_user }}"
    mode: 0755
  with_items:
    - "{{ nifi_conf_dir }}"
    - "{{ nifi_log_dir }}"
    - "{{ nifi_pid_dir }}"
    - "{{ nifi_nar_dir }}"
    - "{{ nifi_work_dir }}"
    - "{{ nifi_etc_dir }}"
    - "{{ nifi_database_repository }}"
    - "{{ nifi_flowfile_repository }}"

- name: ensure nifi content repo directories exist
  file: path="{{ item }}" state=directory owner="{{ nifi_user }}" group="{{ nifi_user }}" mode=0755
  with_items: "{{ nifi_content_repositories }}"

- name: ensure nifi provenance repo directories exist
  file: path="{{ item }}" state=directory owner="{{ nifi_user }}" group="{{ nifi_user }}" mode=0755
  with_items: "{{ nifi_provenance_repositories }}"

- name: ensure zookeeper data directory exists
  file: path="{{ nifi_zookeeper_dir }}" state=directory owner="{{ nifi_user }}" group="{{ nifi_user }}" mode=0755
  when: nifi_state_management_embedded_zookeeper_start

- name: add myid file for embedded zookeeper
  template: src="myid.j2" dest="{{ nifi_zookeeper_dir }}/myid" owner="{{ nifi_user }}" group="{{ nifi_user }}" mode='0644'
  when: nifi_state_management_embedded_zookeeper_start

- name: ensure nifi extra directories exist
  file: path="{{ item }}" state=directory owner="{{ nifi_user }}" group="{{ nifi_user }}" mode=0755
  with_items: "{{ nifi_extra_dirs | default([]) }}"
