---
# vars file for nifi


nifi_service: /etc/systemd/system/nifi.service
nifi_toolkit_service: /etc/systemd/system/nifi-toolkit.service

nifi_home: "{{ nifi_base_dir }}/nifi-current"
nifi_toolkit_home: "{{ nifi_base_dir }}/nifi-toolkit-current"
nifi_conf_dir: "{{ nifi_home }}/conf"
nifi_nar_dir: "{{ nifi_home }}/lib"
nifi_work_dir: "{{ nifi_home }}/work"
nifi_pid_file: "{{ nifi_pid_dir }}/nifi.pid"
nifi_toolkit_pid_file: "{{ nifi_pid_dir }}/nifi-toolkit.pid"
