- name: Install NiFi with proxy gateway
  hosts: docker_nifi
  vars:
      nifi_log_level_root: WARN
      nifi_node_jvm_memory: '4096m'
      nifi_single_node: True
      nifi_proxy_host: "{{ hostvars['test_server']['host'] }}.{{ hostvars['test_server']['domain'] }}" # due to proxy issues
      vault_file_path: ~/repos/ansible-inventory/DSB/encrypted/babelfisk.yml

  roles:
    - role: ../roles/nifi
      nifi_force_restart: False
      nifi_version: 1.6.0
      nifi_is_secure: True
      nifi_tls_token: "thisIsATokenToPreventMITM"
      nifi_single_node: False
      nifi_web_http_port: 8080
      nifi_web_https_port: 8443
      nifi_toolkit_token: thisIsATokenToPreventMITM
      nifi_java_home: '/usr/java/jdk1.8.0_144'
      nifi_hosts:
        - docker7.kb.test
        - docker8.kb.test
        - docker9.kb.test

      nifi_tls_server: docker8.kb.test

      nifi_zookeepers:
        - docker1.kb.test
        - docker2.kb.test
        - docker3.kb.test
      nifi_this_host: "{{ host }}.{{ domain }}.{{ docker_network_name }}"
      nifi_input_socket_host: "{{ nifi_this_host }}"
      # "{{ nifi_proxy_host if host=='docker7' else nifi_this_host }}"

      # Proxy settings
      # NB will not function until release of 1.6 NiFi
      nifi_web_proxy_host_list: "{{ nifi_this_host }}:{{ nifi_web_https_port }}, {{ nifi_proxy_host }}:{{ nifi_web_https_port }}, {{ nifi_proxy_host }}:{{ nifi_web_https_port + 1 }}, {{ nifi_proxy_host }}:{{ nifi_web_https_port + 2 }}"

